name: CI Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    container:
      image: luizelias/windows10

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ./build/HelloWorld

    # Add additional steps as necessary, e.g., for packaging or deploying the build artifacts.
